# Docker Compose for AI Workflow Capstone
# Author: Adryan R A

version: '3.8'

services:
  ai-workflow-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - LOG_LEVEL=INFO
      - DATABASE_PATH=/app/data
      - MODEL_STORAGE_PATH=/app/models
      - LOG_DATABASE_PATH=/app/logs/api_logs.db
    volumes:
      # Mount data directories for persistence
      - api_data:/app/data
      - api_models:/app/models
      - api_logs:/app/logs
      # Mount the training/production data from parent directory
      - ../cs-train:/app/external_data/cs-train:ro
      - ../cs-production:/app/external_data/cs-production:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-workflow-network

  # Optional: Add a monitoring service
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - ai-workflow-network

  # Optional: Add Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - ai-workflow-network

volumes:
  api_data:
    driver: local
  api_models:
    driver: local
  api_logs:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  ai-workflow-network:
    driver: bridge
